'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'al'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation keys - you can expand this or move to separate files
const translations = {
  en: {
    home: 'Home',
    carsTitle: 'Cars',
    apartments: 'Apartments',
    contact: 'Contact',
    signIn: 'Sign In',
    addListing: 'Add Listing',
    skipToContent: 'Skip to content',
    yourJourneyStartsHere: 'Your Journey Starts Here',
    discoverAlbania: 'Discover the beauty of Albania with our premium car rentals and accommodations',
    pickup: 'Pick-up',
    wherePickup: 'Where do you want to pick up?',
    dropoff: 'Drop-off',
    samePlace: 'Same place',
    rentalDates: 'Rental dates',
    pickupTime: 'Pick-up time',
    dropoffTime: 'Drop-off time',
    viewCars: 'View cars',
    days: 'days',
    day: 'day',
    quickFilters: 'Quick Filters',
    automatic: 'Automatic',
    suv: 'SUV',
    budget: 'Under €50/day',
    cancellation: 'Free cancellation',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    whereStay: 'Where do you want to stay?',
    guests: 'Guests',
    search: 'Search',
    featuredCars: 'Featured Cars',
    handpicked: 'Handpicked vehicles for your perfect journey',
    bookNow: 'Book Now',
    popularDestinations: 'Popular Destinations',
    exploreAlbania: 'Explore the most beautiful places in Albania',
    howItWorks: 'How It Works',
    simpleSteps: 'Simple steps to your perfect journey',
    searchSelect: 'Search & Select',
    findPerfectCar: 'Find the perfect car for your needs',
    bookSecurely: 'Book Securely',
    instantConfirmation: 'Get instant confirmation',
    enjoyRide: 'Enjoy Your Ride',
    pickupDrive: 'Pick up and drive away',
    rentalAgency: 'Are you a rental agency?',
    listCarsToday: 'List your cars today and start earning',
    learnMore: 'Learn More',
    easyCalendar: 'Easy Calendar Management',
    conflictAlerts: 'Conflict Alerts',
    instantConfirmations: 'Instant Confirmations',
    verifiedAgencies: 'Verified Agencies',
    allPartnersVetted: 'All our partners are thoroughly vetted',
    securePayments: 'Secure Payments',
    sslEncrypted: 'SSL encrypted transactions',
    support247: '24/7 Support',
    roundClock: 'Round-the-clock customer support',
    freeCancellationOptions: 'Free Cancellation',
    flexiblePolicies: 'Flexible cancellation policies',
    featuredVehicleTypes: 'Vehicle Types',
    chooseVehicle: 'Choose the perfect vehicle for your journey',
    economy: 'Economy',
    compact: 'Compact',
    vanMinivan: 'Van/Minivan',
    luxury: 'Luxury',
    convertibles: 'Convertibles',
    electric: 'Electric',
    // New keys for screenshot design
    rentCarsHotelsVillas: 'Rent Cars Hotels & Villas',
    keywordsPlaceholder: 'Keywords...',
    searchButton: 'SEARCH',
    rentACar: 'Rent a Car',
    hotelsVillas: 'Hotels & Villas',
    exploreOurFleet: 'EXPLORE OUR FLEET',
    // Car listings translations
    findYourPerfectCar: 'Find Your Perfect Car',
    in: 'in',
    from: 'from',
    to: 'to',
    allCars: 'All Cars',
    vehiclesAvailable: 'vehicles available',
    averageRating: 'average rating',
    customerSupport: 'customer support',
    filters: 'Filters',
    clearAll: 'Clear All',
    location: 'Location',
    enterLocation: 'Enter location',
    pickupDate: 'Pickup Date',
    dropoffDate: 'Drop-off Date',
    vehicleType: 'Vehicle Type',
    selectVehicleType: 'Select vehicle type',
    allTypes: 'All Types',
    transmission: 'Transmission',
    selectTransmission: 'Select transmission',
    allTransmissions: 'All Transmissions',
    manual: 'Manual',
    maxPricePerDay: 'Max Price Per Day',
    selectMaxPrice: 'Select max price',
    anyPrice: 'Any Price',
    availableCars: 'Available Cars',
    showingResultsFor: 'Showing results for',
    allLocations: 'all locations',
    sortBy: 'Sort by',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    highestRated: 'Highest Rated',
    mostPopular: 'Most Popular',
    reviews: 'reviews',
    viewDetails: 'View Details',
    loadMoreCars: 'Load More Cars',
    noCarsFound: 'No cars found',
    tryAdjustingFilters: 'Try adjusting your filters or search criteria',
    clearFilters: 'Clear Filters',
    carDetails: 'Car Details',
    detailedCarInformation: 'Detailed car information and specifications',
    bookThisCar: 'Book This Car',
    bookingSidebarPlaceholder: 'Booking sidebar placeholder',
    carDetailsContentPlaceholder: 'Car details content placeholder - you can copy your existing content here',
    // Additional translations for car listings
    loading: {
      title: 'Finding Your Perfect Car',
      subtitle: 'Searching through our fleet...',
    },
    scrollToLoadMore: 'Scroll to load more',
    allCarsLoaded: 'All cars loaded',
    cars: {
      foundCars: 'Found',
      carsText: 'cars',
      total: 'total',
      perDay: 'per day',
      available: 'Available',
      booked: 'Booked',
      recommended: 'Recommended',
      priceLowHigh: 'Price: Low to High',
      priceHighLow: 'Price: High to Low',
      highestRated: 'Highest Rated',
    },
    showOnMap: 'Show on Map',
    previous: 'Previous',
    next: 'Next',
    unavailable: 'Unavailable',
    unlimitedMileage: 'Unlimited Mileage',
    applyFilters: 'Apply Filters',
    mapPlaceholder: 'Interactive Map',
    mapDescription: 'View car locations on the map',
    adjustFilters: 'Adjust Filters',
    searchTips: 'Search Tips',
    tip1: 'Try different date ranges',
    tip2: 'Expand your location search',
    tip3: 'Check different vehicle types',
    // Authentication translations
    userLogin: 'User Login',
    vendorLogin: 'Vendor Login',
    adminLogin: 'Admin Login',
    userLoginDescription: 'Sign in to your account',
    vendorLoginDescription: 'Access your vendor dashboard',
    adminLoginDescription: 'Access the admin panel',
    email: 'Email',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPassword: 'Enter your password',
    signingIn: 'Signing in...',
    loginError: 'Login failed. Please check your credentials.',
    forgotPassword: 'Forgot your password?',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign up',
    // Vendor Portal translations
    vendor: {
      dashboard: 'Dashboard',
      welcomeBack: 'Welcome back to your vendor portal',
      addNewListing: 'Add New Listing',
      totalBookings: 'Total Bookings',
      activeListings: 'Active Listings',
      revenue: 'Revenue',
      customers: 'Customers',
      fromLastMonth: 'from last month',
      newThisWeek: 'new this week',
      recentBookings: 'Recent Bookings',
      quickActions: 'Quick Actions',
      manageListings: 'Manage Listings',
      viewCalendar: 'View Calendar',
      viewAnalytics: 'View Analytics',
      collapse: 'Collapse',
      menu: 'Menu',
      // Cars
      cars: 'Cars',
      addCar: 'Add Car',
      editCar: 'Edit Car',
      carDetails: 'Car Details',
      carMake: 'Car Make',
      model: 'Model',
      year: 'Year',
      bodyType: 'Body Type',
      transmission: 'Transmission',
      fuelType: 'Fuel Type',
      driveType: 'Drive Type',
      seats: 'Seats',
      doors: 'Doors',
      luggage: 'Luggage',
      color: 'Color',
      licensePlate: 'License Plate',
      vin: 'VIN Number',
      selectMake: 'Select make',
      selectType: 'Select type',
      selectTransmission: 'Select transmission',
      selectFuel: 'Select fuel',
      selectDrive: 'Select drive',
      selectYear: 'Select year',
      optional: 'Optional',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      backToCars: 'Back to Cars',
      updateCarListing: 'Update your car rental listing',
      delete: 'Delete',
      edit: 'Edit',
      actions: 'Actions',
      status: 'Status',
      active: 'Active',
      draft: 'Draft',
      inactive: 'Inactive',
      searchCars: 'Search cars...',
      noCarsFound: 'No cars found',
      loadingCars: 'Loading cars...',
      errorLoadingCars: 'Failed to load cars. Please try again.',
      deleteCar: 'Delete Car',
      deleteCarConfirm: 'Are you sure you want to delete this car? This action cannot be undone.',
      deleteCarSuccess: 'Car deleted successfully',
      deleteCarError: 'Failed to delete car. Please try again.',
      // Car Wizard
      basicInformation: 'Basic Information',
      essentialDetails: 'Essential details about your car',
      photos: 'Photos',
      uploadPhotos: 'Upload photos of your car',
      pricing: 'Pricing',
      setPricing: 'Set your pricing and policies',
      availability: 'Availability',
      manageAvailability: 'Manage your car availability',
      publishListing: 'Publish Listing',
      publishing: 'Publishing...',
      selectCarMake: 'Select a car make',
      fillRequiredFields: 'Please fill in all required fields',
      carPublished: 'Car published successfully',
      carPublishError: 'Failed to publish car. Please try again.',
      // Bookings
      bookings: 'Bookings',
      manageBookings: 'Manage your vehicle bookings',
      noBookings: 'No bookings yet.',
      // Analytics
      analytics: 'Analytics',
      // Calendar
      calendar: 'Calendar',
      carAvailabilityCalendar: 'Car Availability Calendar',
      viewManageAvailability: 'View and manage car availability with professional calendar interface',
      month: 'Month',
      week: 'Week',
      list: 'List',
      today: 'Today',
      day: 'Day',
      confirmedBooking: 'Confirmed Booking',
      pendingBooking: 'Pending Booking',
      cancelledBooking: 'Cancelled Booking',
      // Settings
      settings: 'Settings',
      settingsPlaceholder: 'Manage your account settings and preferences',
      // Apartments
      apartments: 'Apartments',
      addApartment: 'Add Apartment',
      editApartment: 'Edit Apartment',
      // Car Wizard additional strings
      basicCarInformation: 'Basic Car Information',
      enterBasicDetails: 'Enter the basic details about your vehicle',
      enterExactModel: 'Enter the exact model name',
      privateInformation: 'Private information, not shown to customers',
      forInsuranceVerification: 'For insurance and verification purposes',
      addHighQualityPhotos: 'Add high-quality photos of your car (minimum 3 photos required)',
      photosIncreaseBookings: 'High-quality photos increase booking rates by up to 40%. Include exterior, interior, and engine photos.',
      dragDropPhotos: 'Drag & drop photos here',
      clickToBrowse: 'or click to browse files (JPEG, PNG up to 10MB each)',
      browseFiles: 'Browse Files',
      uploadedPhotos: 'Uploaded Photos',
      coverPhoto: 'Cover Photo',
      setAsCover: 'Set as Cover',
      onlyImageFilesAllowed: 'Only image files are allowed.',
      carCreatedButImageUploadFailed: 'Car created successfully, but image upload failed. You can add images later.',
      carUpdatedButImageUploadFailed: 'Car updated successfully, but image upload failed. You can add images later.',
      manageCarImages: 'Manage your car images. Upload new images or delete existing ones.',
      existingImages: 'Existing Images',
      uploadNewImages: 'Upload New Images',
      newImagesToUpload: 'New Images to Upload',
      new: 'New',
      deleteImage: 'Delete Image',
      deleteImageConfirm: 'Are you sure you want to delete this image? This action cannot be undone.',
      deleting: 'Deleting...',
      maxImagesReached: 'Maximum 4 images allowed',
      deleteImageToUploadMore: 'Please delete an existing image to upload a new one.',
      photoTips: 'Photo Tips:',
      takePhotosGoodLighting: 'Take photos in good lighting (natural daylight preferred)',
      cleanCarBefore: 'Clean your car before photographing',
      includeAllAngles: 'Include exterior from all angles, interior, dashboard, and trunk',
      avoidBlurryPhotos: 'Avoid blurry or dark photos',
      pricingPolicies: 'Pricing & Policies',
      setRentalRates: 'Set your rental rates and policies',
      basePricing: 'Base Pricing',
      dailyRate: 'Daily Rate (€)',
      competitiveRates: 'Competitive rates: €25-150/day',
      weeklyDiscount: 'Weekly Discount (%)',
      monthlyDiscount: 'Monthly Discount (%)',
      seasonalPricing: 'Seasonal Pricing',
      configureDifferentRates: 'Configure different rates for peak seasons, holidays, and special events',
      addSeason: 'Add Season',
      seasonName: 'Season name (e.g., Summer 2024)',
      startDate: 'Start Date',
      endDate: 'End Date',
      seasonType: 'Season Type',
      standard: 'Standard',
      peakSeason: 'Peak Season',
      offSeason: 'Off Season',
      priceCalendarPreview: 'Price Calendar Preview',
      selectDatePreview: 'Select date to preview pricing',
      legend: 'Legend:',
      additionalFees: 'Additional Fees (Optional)',
      extraDriverFee: 'Extra Driver Fee (€)',
      airportDelivery: 'Airport Delivery (€)',
      childSeatFee: 'Child Seat Fee (€/day)',
      securityDeposit: 'Security Deposit',
      requireSecurityDeposit: 'Require security deposit',
      depositAmount: 'Deposit Amount (€)',
      rentalPolicies: 'Rental Policies',
      fuelPolicy: 'Fuel Policy',
      returnSameFuel: 'Return with same fuel level',
      returnFullTank: 'Return full tank',
      prepaidFuel: 'Pre-paid fuel',
      cancellationPolicy: 'Cancellation Policy',
      flexibleCancellation: 'Flexible (free cancellation 24h before)',
      moderateCancellation: 'Moderate (free cancellation 48h before)',
      strictCancellation: 'Strict (free cancellation 7 days before)',
      dailyMileageLimit: 'Daily Mileage Limit (km)',
      leaveEmptyUnlimited: 'Leave empty for unlimited',
      overageFee: 'Overage Fee (€/km)',
      availabilitySettings: 'Availability Settings',
      setWhenAvailable: 'Set when your car is available for rent',
      keepCalendarUpdated: 'Keep your calendar updated to avoid booking conflicts.',
      alwaysAvailable: 'Always available (can be booked anytime)',
      selectDatesBlock: 'Select dates to block or set special pricing',
      selectDatesToBlock: 'Select dates to block',
      blockSelectedDates: 'Block Selected Dates',
      clearSelection: 'Clear Selection',
      blockSelectedDate: 'Block selected date',
      setSpecialPrice: 'Set special price',
      blockAllWeekends: 'Block all weekends (next 3 months)',
      setSummerPricing: 'Set summer pricing (June-August)',
      calendarLegend: 'Calendar Legend',
      available: 'Available',
      booked: 'Booked',
      blockedByYou: 'Blocked by you',
      specialPrice: 'Special price',
      addNewCar: 'Add New Car',
      followSteps: 'Follow these steps to create your car listing',
      step: 'Step',
      basics: 'Basics',
      pricingPoliciesShort: 'Pricing & Policies',
      saveExit: 'Save & Exit',
      back: 'Back',
      next: 'Next',
      pleaseSelectCarMake: 'Please select a car make.',
      pleaseFillRequiredFields: 'Please fill in all required fields.',
    },
  },
  al: {
    home: 'Ballina',
    carsTitle: 'Makinat',
    apartments: 'Apartamentet',
    contact: 'Kontakti',
    signIn: 'Hyr',
    addListing: 'Shto Listim',
    skipToContent: 'Kalo në përmbajtje',
    yourJourneyStartsHere: 'Udhëtimi Juaj Fillon Këtu',
    discoverAlbania: 'Zbuloni bukurinë e Shqipërisë me makinat dhe akomodimet tona premium',
    pickup: 'Marrja',
    wherePickup: 'Ku doni të merrni makinën?',
    dropoff: 'Dorëzimi',
    samePlace: 'I njëjti vend',
    rentalDates: 'Datat e qirasë',
    pickupTime: 'Koha e marrjes',
    dropoffTime: 'Koha e dorëzimit',
    viewCars: 'Shiko makinat',
    days: 'ditë',
    day: 'ditë',
    quickFilters: 'Filtrat e Shpejtë',
    automatic: 'Automatik',
    suv: 'SUV',
    budget: 'Nën €50/ditë',
    cancellation: 'Anulim falas',
    checkIn: 'Regjistrimi',
    checkOut: 'Çregjistrimi',
    whereStay: 'Ku doni të qëndroni?',
    guests: 'Të ftuar',
    search: 'Kërko',
    featuredCars: 'Makinat e Rekomanduara',
    handpicked: 'Makinat e zgjedhura për udhëtimin tuaj të përsosur',
    popularDestinations: 'Destinacionet Popullore',
    exploreAlbania: 'Eksploroni vendet më të bukura në Shqipëri',
    howItWorks: 'Si Funksionon',
    simpleSteps: 'Hapa të thjeshtë për udhëtimin tuaj të përsosur',
    searchSelect: 'Kërko dhe Zgjidh',
    findPerfectCar: 'Gjej makinën e përsosur për nevojat e tua',
    bookSecurely: 'Rezervo Sigurt',
    instantConfirmation: 'Merr konfirmim të menjëhershëm',
    enjoyRide: 'Gëzo Udhëtimin',
    pickupDrive: 'Merr dhe nisu',
    rentalAgency: 'A jeni agjensi qiraje?',
    listCarsToday: 'Listoni makinat tuaja sot dhe filloni të fitoni',
    learnMore: 'Mëso Më Shumë',
    easyCalendar: 'Menaxhimi i Lehtë i Kalendarit',
    conflictAlerts: 'Sinjalizimet e Konfliktit',
    instantConfirmations: 'Konfirmimet e Menjëhershme',
    verifiedAgencies: 'Agjensi të Verifikuara',
    allPartnersVetted: 'Të gjithë partnerët tanë janë kontrolluar plotësisht',
    securePayments: 'Pagesa të Sigurta',
    sslEncrypted: 'Transaksione të enkriptuara SSL',
    support247: 'Mbështetje 24/7',
    roundClock: 'Mbështetje klienti gjatë gjithë orës',
    freeCancellationOptions: 'Anulim Falas',
    flexiblePolicies: 'Politika fleksibile anulimi',
    featuredVehicleTypes: 'Llojet e Automjeteve',
    chooseVehicle: 'Zgjidhni automjetin e përsosur për udhëtimin tuaj',
    economy: 'Ekonomik',
    compact: 'Kompakt',
    vanMinivan: 'Furgon/Minivan',
    luxury: 'Luksoz',
    convertibles: 'Kabriolet',
    electric: 'Elektrik',
    // New keys for screenshot design
    rentCarsHotelsVillas: 'Qira Makinash Hotele & Vila',
    keywordsPlaceholder: 'Fjalë kyçe...',
    searchButton: 'KËRKO',
    rentACar: 'Qira Makine',
    hotelsVillas: 'Hotele & Vila',
    exploreOurFleet: 'EKSPLORO FLOTËN TONË',
    bookNow: 'REZERVO TANI',
    // Car listings translations
    findYourPerfectCar: 'Gjej Makinën Tënde Të Përsosur',
    in: 'në',
    from: 'nga',
    to: 'deri',
    allCars: 'Të Gjitha Makinat',
    vehiclesAvailable: 'automjete të disponueshme',
    averageRating: 'vlerësim mesatar',
    customerSupport: 'mbështetje klienti',
    filters: 'Filtrat',
    clearAll: 'Pastro Të Gjitha',
    location: 'Vendi',
    enterLocation: 'Shkruaj vendin',
    pickupDate: 'Data e Marrjes',
    dropoffDate: 'Data e Dorëzimit',
    vehicleType: 'Lloji i Automjetit',
    selectVehicleType: 'Zgjidh llojin e automjetit',
    allTypes: 'Të Gjitha Llojet',
    transmission: 'Kambio',
    selectTransmission: 'Zgjidh llojin e kambios',
    allTransmissions: 'Të Gjitha Transmetimet',
    manual: 'Manuale',
    maxPricePerDay: 'Çmimi Maksimal Për Ditë',
    selectMaxPrice: 'Zgjidh çmimin maksimal',
    anyPrice: 'Çdo Çmim',
    availableCars: 'Makinat e Disponueshme',
    showingResultsFor: 'Duke treguar rezultatet për',
    allLocations: 'të gjitha vendet',
    sortBy: 'Rendit sipas',
    priceLowToHigh: 'Çmimi: Nga i Uli në i Lartë',
    priceHighToLow: 'Çmimi: Nga i Lartë në i Uli',
    highestRated: 'Më të Vlerësuarat',
    mostPopular: 'Më të Popullarizuarat',
    reviews: 'vlerësime',
    viewDetails: 'Shiko Detajet',
    loadMoreCars: 'Ngarko Më Shumë Makina',
    noCarsFound: 'Nuk u gjetën makina',
    tryAdjustingFilters: 'Provo të rregullosh filtrat ose kriteret e kërkimit',
    clearFilters: 'Pastro Filtrat',
    carDetails: 'Detajet e Makinës',
    detailedCarInformation: 'Informacione të detajuara të makinës dhe specifikime',
    bookThisCar: 'Rezervo Këtë Makinë',
    bookingSidebarPlaceholder: 'Vendmbajtës i anës së rezervimit',
    carDetailsContentPlaceholder: 'Vendmbajtës i përmbajtjes së detajeve të makinës - mund të kopjosh përmbajtjen ekzistuese këtu',
    // Additional translations for car listings
    loading: {
      title: 'Duke Gjetur Makinën Tënde Të Përsosur',
      subtitle: 'Duke kërkuar në flotën tonë...',
    },
    scrollToLoadMore: 'Lëviz për të ngarkuar më shumë',
    allCarsLoaded: 'Të gjitha makinat u ngarkuan',
    cars: {
      foundCars: 'U gjetën',
      carsText: 'makina',
      total: 'total',
      perDay: 'për ditë',
      available: 'E Disponueshme',
      booked: 'E Rezervuar',
      recommended: 'E Rekomanduar',
      priceLowHigh: 'Çmimi: Nga i Uli në i Lartë',
      priceHighLow: 'Çmimi: Nga i Lartë në i Uli',
      highestRated: 'Më të Vlerësuarat',
    },
    showOnMap: 'Shiko në Hartë',
    previous: 'Mëparshme',
    next: 'Tjetra',
    unavailable: 'E Padisponueshme',
    unlimitedMileage: 'Kilometrazh i Pakufizuar',
    applyFilters: 'Apliko Filtrat',
    mapPlaceholder: 'Harta Interaktive',
    mapDescription: 'Shiko vendndodhjet e makinave në hartë',
    adjustFilters: 'Rregullo Filtrat',
    searchTips: 'Këshilla për Kërkim',
    tip1: 'Provo vargje të ndryshme datash',
    tip2: 'Zgjero kërkimin e vendit',
    tip3: 'Kontrollo lloje të ndryshme automjetesh',
    // Authentication translations
    userLogin: 'Hyrja e Përdoruesit',
    vendorLogin: 'Hyrja e Furnizuesit',
    adminLogin: 'Hyrja e Administratorit',
    userLoginDescription: 'Hyni në llogarinë tuaj',
    vendorLoginDescription: 'Qasuni në panelin e furnizuesit',
    adminLoginDescription: 'Qasuni në panelin e administratorit',
    email: 'Email',
    enterEmail: 'Shkruani email-in tuaj',
    password: 'Fjalëkalimi',
    enterPassword: 'Shkruani fjalëkalimin tuaj',
    signingIn: 'Duke u futur...',
    loginError: 'Hyrja dështoi. Ju lutemi kontrolloni kredencialet tuaja.',
    forgotPassword: 'Keni harruar fjalëkalimin?',
    dontHaveAccount: 'Nuk keni llogari?',
    signUp: 'Regjistrohuni',
    // Vendor Portal translations
    vendor: {
      dashboard: 'Paneli',
      welcomeBack: 'Mirë se vini në panelin e furnizuesit',
      addNewListing: 'Shto Listim të Ri',
      totalBookings: 'Rezervimet Totale',
      activeListings: 'Listimet Aktive',
      revenue: 'Të Ardhurat',
      customers: 'Klientët',
      fromLastMonth: 'nga muaji i kaluar',
      newThisWeek: 'të reja këtë javë',
      recentBookings: 'Rezervimet e Fundit',
      quickActions: 'Veprimet e Shpejta',
      manageListings: 'Menaxho Listimet',
      viewCalendar: 'Shiko Kalendarin',
      viewAnalytics: 'Shiko Analitikën',
      collapse: 'Mbyll',
      menu: 'Menu',
      // Cars
      cars: 'Makinat',
      addCar: 'Shto Makinë',
      editCar: 'Ndrysho Makinë',
      carDetails: 'Detajet e Makinës',
      carMake: 'Marka e Makinës',
      model: 'Modeli',
      year: 'Viti',
      bodyType: 'Lloji i Trupit',
      transmission: 'Kambio',
      fuelType: 'Lloji i Karburantit',
      driveType: 'Lloji i Drejtimit',
      seats: 'Vendet',
      doors: 'Dyert',
      luggage: 'Bagazhi',
      color: 'Ngjyra',
      licensePlate: 'Targat',
      vin: 'Numri VIN',
      selectMake: 'Zgjidh markën',
      selectType: 'Zgjidh llojin',
      selectTransmission: 'Zgjidh llojin e kambios',
      selectFuel: 'Zgjidh karburantin',
      selectDrive: 'Zgjidh drejtimin',
      selectYear: 'Zgjidh vitin',
      optional: 'Opsionale',
      saveChanges: 'Ruaj Ndryshimet',
      cancel: 'Anulo',
      backToCars: 'Kthehu te Makinat',
      updateCarListing: 'Përditëso listimin e makinës',
      delete: 'Fshi',
      edit: 'Ndrysho',
      actions: 'Veprimet',
      status: 'Statusi',
      active: 'Aktive',
      draft: 'Draft',
      inactive: 'Joaktive',
      searchCars: 'Kërko makina...',
      noCarsFound: 'Nuk u gjetën makina',
      loadingCars: 'Duke ngarkuar makinat...',
      errorLoadingCars: 'Dështoi ngarkimi i makinave. Ju lutemi provoni përsëri.',
      deleteCar: 'Fshi Makinën',
      deleteCarConfirm: 'Jeni të sigurt që doni të fshini këtë makinë? Ky veprim nuk mund të zhbëhet.',
      deleteCarSuccess: 'Makina u fshi me sukses',
      deleteCarError: 'Dështoi fshirja e makinës. Ju lutemi provoni përsëri.',
      // Car Wizard
      basicInformation: 'Informacioni Bazë',
      essentialDetails: 'Detajet thelbësore për makinën tuaj',
      photos: 'Foto',
      uploadPhotos: 'Ngarko foto të makinës suaj',
      pricing: 'Çmimi',
      setPricing: 'Vendos çmimin dhe politikën tuaj',
      availability: 'Disponueshmëria',
      manageAvailability: 'Menaxho disponueshmërinë e makinës',
      publishListing: 'Publiko Listimin',
      publishing: 'Duke publikuar...',
      selectCarMake: 'Zgjidh një markë makine',
      fillRequiredFields: 'Ju lutemi plotësoni të gjitha fushat e kërkuara',
      carPublished: 'Makina u publikua me sukses',
      carPublishError: 'Dështoi publikimi i makinës. Ju lutemi provoni përsëri.',
      // Bookings
      bookings: 'Rezervimet',
      manageBookings: 'Menaxho rezervimet e automjeteve',
      noBookings: 'Nuk ka rezervime ende.',
      // Analytics
      analytics: 'Analitika',
      // Calendar
      calendar: 'Kalendari',
      carAvailabilityCalendar: 'Kalendari i Disponueshmërisë së Makinave',
      viewManageAvailability: 'Shikoni dhe menaxhoni disponueshmërinë e makinave me një ndërfaqe kalendari profesionale',
      month: 'Muaj',
      week: 'Javë',
      list: 'Listë',
      today: 'Sot',
      day: 'Ditë',
      confirmedBooking: 'Rezervim i Konfirmuar',
      pendingBooking: 'Rezervim në Pritje',
      cancelledBooking: 'Rezervim i Anuluar',
      // Settings
      settings: 'Cilësimet',
      settingsPlaceholder: 'Menaxho cilësimet dhe preferencat e llogarisë suaj',
      // Apartments
      apartments: 'Apartamentet',
      addApartment: 'Shto Apartament',
      editApartment: 'Ndrysho Apartament',
      // Car Wizard additional strings
      basicCarInformation: 'Informacioni Bazë i Makinës',
      enterBasicDetails: 'Shkruani detajet bazë për automjetin tuaj',
      enterExactModel: 'Shkruani emrin e saktë të modelit',
      privateInformation: 'Informacion privat, nuk shfaqet për klientët',
      forInsuranceVerification: 'Për qëllime sigurimi dhe verifikimi',
      addHighQualityPhotos: 'Shtoni foto me cilësi të lartë të makinës suaj (kërkohen të paktën 3 foto)',
      photosIncreaseBookings: 'Fotot me cilësi të lartë rrisin normat e rezervimit deri në 40%. Përfshini foto të jashtme, të brendshme dhe motorit.',
      dragDropPhotos: 'Tërhiq dhe lësho foto këtu',
      clickToBrowse: 'ose kliko për të zgjedhur skedarët (JPEG, PNG deri në 10MB secili)',
      browseFiles: 'Zgjidh Skedarët',
      uploadedPhotos: 'Foto të Ngarkuara',
      coverPhoto: 'Foto Kopertine',
      setAsCover: 'Vendos si Kopertinë',
      onlyImageFilesAllowed: 'Lejohen vetëm skedarë imazhi.',
      carCreatedButImageUploadFailed: 'Makina u krijua me sukses, por ngarkimi i fotove dështoi. Mund të shtoni foto më vonë.',
      carUpdatedButImageUploadFailed: 'Makina u përditësua me sukses, por ngarkimi i fotove dështoi. Mund të shtoni foto më vonë.',
      manageCarImages: 'Menaxhoni fotot e makinës suaj. Ngarkoni foto të reja ose fshini ato ekzistuese.',
      existingImages: 'Foto Ekzistuese',
      uploadNewImages: 'Ngarko Foto të Reja',
      newImagesToUpload: 'Foto të Reja për të Ngarkuar',
      new: 'E Re',
      deleteImage: 'Fshi Foton',
      deleteImageConfirm: 'Jeni të sigurt që dëshironi të fshini këtë foto? Ky veprim nuk mund të zhbëhet.',
      deleting: 'Duke fshirë...',
      maxImagesReached: 'Lejohen maksimumi 4 foto',
      deleteImageToUploadMore: 'Ju lutemi fshini një foto ekzistuese për të ngarkuar një të re.',
      photoTips: 'Këshilla për Foto:',
      takePhotosGoodLighting: 'Merrni foto në dritë të mirë (preferohet drita natyrore e ditës)',
      cleanCarBefore: 'Pastroni makinën para fotografimit',
      includeAllAngles: 'Përfshini të jashtmen nga të gjitha këndet, të brendshmen, tabelën e instrumenteve dhe bagazhin',
      avoidBlurryPhotos: 'Shmangni foto të paqarta ose të errëta',
      pricingPolicies: 'Çmimi dhe Politikët',
      setRentalRates: 'Vendosni tarifat dhe politikën tuaj të qirasë',
      basePricing: 'Çmimi Bazë',
      dailyRate: 'Tarifa Ditore (€)',
      competitiveRates: 'Tarifa konkurruese: €25-150/ditë',
      weeklyDiscount: 'Zbritje Javore (%)',
      monthlyDiscount: 'Zbritje Mujore (%)',
      seasonalPricing: 'Çmimi Sipas Sezonit',
      configureDifferentRates: 'Konfiguroni tarifa të ndryshme për sezonet e pikut, pushimet dhe ngjarjet speciale',
      addSeason: 'Shto Sezon',
      seasonName: 'Emri i sezonit (p.sh., Verë 2024)',
      startDate: 'Data e Fillimit',
      endDate: 'Data e Mbarimit',
      seasonType: 'Lloji i Sezonit',
      standard: 'Standard',
      peakSeason: 'Sezoni i Pikut',
      offSeason: 'Sezoni i Jashtëm',
      priceCalendarPreview: 'Parapamje e Kalendarit të Çmimeve',
      selectDatePreview: 'Zgjidh datën për të parë çmimin',
      legend: 'Legjenda:',
      additionalFees: 'Tarifa Shtesë (Opsionale)',
      extraDriverFee: 'Tarifa për Shofer Shtesë (€)',
      airportDelivery: 'Dorëzimi në Aeroport (€)',
      childSeatFee: 'Tarifa për Karrige Fëmijësh (€/ditë)',
      securityDeposit: 'Depozita e Sigurisë',
      requireSecurityDeposit: 'Kërko depozitë sigurie',
      depositAmount: 'Shuma e Depozitës (€)',
      rentalPolicies: 'Politikat e Qirasë',
      fuelPolicy: 'Politika e Karburantit',
      returnSameFuel: 'Kthe me të njëjtin nivel karburanti',
      returnFullTank: 'Kthe me rezervuar të plotë',
      prepaidFuel: 'Karburant i paguar paraprakisht',
      cancellationPolicy: 'Politika e Anulimit',
      flexibleCancellation: 'Fleksibël (anulim falas 24 orë para)',
      moderateCancellation: 'Moderate (anulim falas 48 orë para)',
      strictCancellation: 'I rreptë (anulim falas 7 ditë para)',
      dailyMileageLimit: 'Kufiri i Kilometrazhit Ditë (km)',
      leaveEmptyUnlimited: 'Lëreni bosh për të pakufizuar',
      overageFee: 'Tarifa për Kilometrazh Shtesë (€/km)',
      availabilitySettings: 'Cilësimet e Disponueshmërisë',
      setWhenAvailable: 'Vendosni kur makina juaj është e disponueshme për qira',
      keepCalendarUpdated: 'Mbani kalendarin tuaj të përditësuar për të shmangur konfliktet e rezervimit.',
      alwaysAvailable: 'Gjithmonë e disponueshme (mund të rezervohet në çdo kohë)',
      selectDatesBlock: 'Zgjidhni datat për t\'i bllokuar ose për të vendosur çmim special',
      selectDatesToBlock: 'Zgjidhni datat për t\'i bllokuar',
      blockSelectedDates: 'Blloko Datat e Zgjedhura',
      clearSelection: 'Pastro Zgjedhjen',
      blockSelectedDate: 'Blloko datën e zgjedhur',
      setSpecialPrice: 'Vendos çmim special',
      blockAllWeekends: 'Blloko të gjitha fundjavët (3 muajt e ardhshëm)',
      setSummerPricing: 'Vendos çmimin e verës (Qershor-Gusht)',
      calendarLegend: 'Legjenda e Kalendarit',
      available: 'E Disponueshme',
      booked: 'E Rezervuar',
      blockedByYou: 'E bllokuar nga ju',
      specialPrice: 'Çmim special',
      addNewCar: 'Shto Makinë të Re',
      followSteps: 'Ndiqni këto hapa për të krijuar listimin tuaj të makinës',
      step: 'Hapi',
      basics: 'Bazat',
      pricingPoliciesShort: 'Çmimi dhe Politikët',
      saveExit: 'Ruaj dhe Dil',
      back: 'Kthehu',
      next: 'Tjetra',
      pleaseSelectCarMake: 'Ju lutemi zgjidhni një markë makine.',
      pleaseFillRequiredFields: 'Ju lutemi plotësoni të gjitha fushat e kërkuara.',
    },
  },
}

interface LanguageProviderProps {
  children: React.ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('en')

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'al')) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: string | Record<string, unknown> = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k] as string | Record<string, unknown>;
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
